// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtCjB878XFTh2g-7NCVaQAhRdevcCHqE',
    appId: '1:1549963633:web:b1afa3286a5427aa8566d0',
    messagingSenderId: '1549963633',
    projectId: 'coffee-order-8a3a3',
    authDomain: 'coffee-order-8a3a3.firebaseapp.com',
    storageBucket: 'coffee-order-8a3a3.appspot.com',
    measurementId: 'G-WJ8S6PJVDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgE89D9Z7wC41MZg8_jZ-xPpXe_DeQBo',
    appId: '1:1549963633:android:17b92bdfad5298a98566d0',
    messagingSenderId: '1549963633',
    projectId: 'coffee-order-8a3a3',
    storageBucket: 'coffee-order-8a3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZBIbU3EfmaboOwV_0TYBws3OMcLAXIM',
    appId: '1:1549963633:ios:1aad57dcf72f12438566d0',
    messagingSenderId: '1549963633',
    projectId: 'coffee-order-8a3a3',
    storageBucket: 'coffee-order-8a3a3.appspot.com',
    iosClientId: '1549963633-4k1tjounfrbijed71i28dsnj4d34nkli.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZBIbU3EfmaboOwV_0TYBws3OMcLAXIM',
    appId: '1:1549963633:ios:3ed0ed7acc442b958566d0',
    messagingSenderId: '1549963633',
    projectId: 'coffee-order-8a3a3',
    storageBucket: 'coffee-order-8a3a3.appspot.com',
    iosClientId: '1549963633-un37re6nqdi3s1cq1km5gab8n7s2fg7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeConnect.RunnerTests',
  );
}
